name: 'MKFL'

services:
  flsrv:
    image: mkfl
    networks:
      - fl
    entrypoint: [ "bash", "-c", "FL/docker_se.sh ${NCLIENTS} ${NROUNDS} ${DATASET} ${MODEL} ${ISENC}"]
    volumes:
      - ${FILEPATH}/:/results
      - ${DATABASEPATH}/:/mkfl/databases
      - /var/run/docker.sock:/var/run/docker.sock
  flcl:
    image: mkfl
    networks:
      - fl
    deploy:
      mode: replicated
      replicas: ${NCLIENTS}
    entrypoint: [ "bash", "-c", "FL/docker_cl.sh ${NCLIENTS} ${NROUNDS} ${DATASET} ${MODEL} ${ISENC}"]
    volumes:
      - ${FILEPATH}/:/results
      - ${DATABASEPATH}/:/mkfl/databases
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  fl:
    driver: bridge

volumes:
  fl-results:
