"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2020 Flower Labs GmbH. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Code:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _CodeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Code.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    OK: _Code.ValueType  # 0
    GET_PROPERTIES_NOT_IMPLEMENTED: _Code.ValueType  # 1
    GET_PARAMETERS_NOT_IMPLEMENTED: _Code.ValueType  # 2
    FIT_NOT_IMPLEMENTED: _Code.ValueType  # 3
    EVALUATE_NOT_IMPLEMENTED: _Code.ValueType  # 4

class Code(_Code, metaclass=_CodeEnumTypeWrapper): ...

OK: Code.ValueType  # 0
GET_PROPERTIES_NOT_IMPLEMENTED: Code.ValueType  # 1
GET_PARAMETERS_NOT_IMPLEMENTED: Code.ValueType  # 2
FIT_NOT_IMPLEMENTED: Code.ValueType  # 3
EVALUATE_NOT_IMPLEMENTED: Code.ValueType  # 4
global___Code = Code

class _Reason:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ReasonEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Reason.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNKNOWN: _Reason.ValueType  # 0
    RECONNECT: _Reason.ValueType  # 1
    POWER_DISCONNECTED: _Reason.ValueType  # 2
    WIFI_UNAVAILABLE: _Reason.ValueType  # 3
    ACK: _Reason.ValueType  # 4

class Reason(_Reason, metaclass=_ReasonEnumTypeWrapper): ...

UNKNOWN: Reason.ValueType  # 0
RECONNECT: Reason.ValueType  # 1
POWER_DISCONNECTED: Reason.ValueType  # 2
WIFI_UNAVAILABLE: Reason.ValueType  # 3
ACK: Reason.ValueType  # 4
global___Reason = Reason

@typing_extensions.final
class Status(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    code: global___Code.ValueType
    message: builtins.str
    def __init__(
        self,
        *,
        code: global___Code.ValueType = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["code", b"code", "message", b"message"]) -> None: ...

global___Status = Status

@typing_extensions.final
class Parameters(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TENSORS_FIELD_NUMBER: builtins.int
    TENSOR_TYPE_FIELD_NUMBER: builtins.int
    @property
    def tensors(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    tensor_type: builtins.str
    def __init__(
        self,
        *,
        tensors: collections.abc.Iterable[builtins.bytes] | None = ...,
        tensor_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["tensor_type", b"tensor_type", "tensors", b"tensors"]) -> None: ...

global___Parameters = Parameters

@typing_extensions.final
class ServerMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class ReconnectIns(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SECONDS_FIELD_NUMBER: builtins.int
        seconds: builtins.int
        def __init__(
            self,
            *,
            seconds: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["seconds", b"seconds"]) -> None: ...

    @typing_extensions.final
    class GetPropertiesIns(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class ConfigEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            @property
            def value(self) -> global___Scalar: ...
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: global___Scalar | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

        CONFIG_FIELD_NUMBER: builtins.int
        @property
        def config(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Scalar]: ...
        def __init__(
            self,
            *,
            config: collections.abc.Mapping[builtins.str, global___Scalar] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["config", b"config"]) -> None: ...

    @typing_extensions.final
    class GetParametersIns(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class ConfigEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            @property
            def value(self) -> global___Scalar: ...
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: global___Scalar | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

        CONFIG_FIELD_NUMBER: builtins.int
        @property
        def config(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Scalar]: ...
        def __init__(
            self,
            *,
            config: collections.abc.Mapping[builtins.str, global___Scalar] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["config", b"config"]) -> None: ...

    @typing_extensions.final
    class FitIns(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class ConfigEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            @property
            def value(self) -> global___Scalar: ...
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: global___Scalar | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

        PARAMETERS_FIELD_NUMBER: builtins.int
        CONFIG_FIELD_NUMBER: builtins.int
        @property
        def parameters(self) -> global___Parameters: ...
        @property
        def config(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Scalar]: ...
        def __init__(
            self,
            *,
            parameters: global___Parameters | None = ...,
            config: collections.abc.Mapping[builtins.str, global___Scalar] | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["parameters", b"parameters"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["config", b"config", "parameters", b"parameters"]) -> None: ...

    @typing_extensions.final
    class EvaluateIns(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class ConfigEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            @property
            def value(self) -> global___Scalar: ...
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: global___Scalar | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

        PARAMETERS_FIELD_NUMBER: builtins.int
        CONFIG_FIELD_NUMBER: builtins.int
        @property
        def parameters(self) -> global___Parameters: ...
        @property
        def config(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Scalar]: ...
        def __init__(
            self,
            *,
            parameters: global___Parameters | None = ...,
            config: collections.abc.Mapping[builtins.str, global___Scalar] | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["parameters", b"parameters"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["config", b"config", "parameters", b"parameters"]) -> None: ...

    @typing_extensions.final
    class GetPKIns(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CTX_FIELD_NUMBER: builtins.int
        ctx: builtins.bytes
        def __init__(
            self,
            *,
            ctx: builtins.bytes = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["ctx", b"ctx"]) -> None: ...

    @typing_extensions.final
    class SendPKIns(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CTX_FIELD_NUMBER: builtins.int
        ctx: builtins.bytes
        def __init__(
            self,
            *,
            ctx: builtins.bytes = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["ctx", b"ctx"]) -> None: ...

    @typing_extensions.final
    class GetParmsIns(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    @typing_extensions.final
    class SendEncIns(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CTX_FIELD_NUMBER: builtins.int
        ENC_FIELD_NUMBER: builtins.int
        ctx: builtins.bytes
        enc: builtins.bytes
        def __init__(
            self,
            *,
            ctx: builtins.bytes = ...,
            enc: builtins.bytes = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["ctx", b"ctx", "enc", b"enc"]) -> None: ...

    @typing_extensions.final
    class SendDSIns(google.protobuf.message.Message):
        """message SendDSIns{
         bytes ctx = 1;
         bytes ds = 2;
        }
        """

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class ConfigEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            @property
            def value(self) -> global___Scalar: ...
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: global___Scalar | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

        PARAMETERS_FIELD_NUMBER: builtins.int
        CONFIG_FIELD_NUMBER: builtins.int
        @property
        def parameters(self) -> global___Parameters: ...
        @property
        def config(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Scalar]: ...
        def __init__(
            self,
            *,
            parameters: global___Parameters | None = ...,
            config: collections.abc.Mapping[builtins.str, global___Scalar] | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["parameters", b"parameters"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["config", b"config", "parameters", b"parameters"]) -> None: ...

    @typing_extensions.final
    class SendEvalIns(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    @typing_extensions.final
    class GetGradientsIns(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    @typing_extensions.final
    class IdentifyIns(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    @typing_extensions.final
    class GetContributionsIns(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        GRADIENTS_FIELD_NUMBER: builtins.int
        @property
        def gradients(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
        def __init__(
            self,
            *,
            gradients: collections.abc.Iterable[builtins.bytes] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["gradients", b"gradients"]) -> None: ...

    @typing_extensions.final
    class SendSumIns(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        STATUS_FIELD_NUMBER: builtins.int
        SUM_FIELD_NUMBER: builtins.int
        status: builtins.str
        @property
        def sum(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        def __init__(
            self,
            *,
            status: builtins.str | None = ...,
            sum: collections.abc.Iterable[builtins.int] | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["_status", b"_status", "status", b"status"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["_status", b"_status", "status", b"status", "sum", b"sum"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions.Literal["_status", b"_status"]) -> typing_extensions.Literal["status"] | None: ...

    @typing_extensions.final
    class SendPublicKeyIns(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        PUBLICKEY_FIELD_NUMBER: builtins.int
        @property
        def publickey(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
        def __init__(
            self,
            *,
            publickey: collections.abc.Iterable[builtins.str] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["publickey", b"publickey"]) -> None: ...

    RECONNECT_INS_FIELD_NUMBER: builtins.int
    GET_PROPERTIES_INS_FIELD_NUMBER: builtins.int
    GET_PARAMETERS_INS_FIELD_NUMBER: builtins.int
    FIT_INS_FIELD_NUMBER: builtins.int
    EVALUATE_INS_FIELD_NUMBER: builtins.int
    SEND_SUM_INS_FIELD_NUMBER: builtins.int
    GET_PK_INS_FIELD_NUMBER: builtins.int
    SEND_PK_INS_FIELD_NUMBER: builtins.int
    GET_PARMS_INS_FIELD_NUMBER: builtins.int
    SEND_ENC_INS_FIELD_NUMBER: builtins.int
    SEND_DS_INS_FIELD_NUMBER: builtins.int
    SEND_EVAL_INS_FIELD_NUMBER: builtins.int
    GET_GRADIENTS_INS_FIELD_NUMBER: builtins.int
    IDENTIFY_INS_FIELD_NUMBER: builtins.int
    GET_CONTRIBUTIONS_INS_FIELD_NUMBER: builtins.int
    SEND_PUBLIC_KEY_INS_FIELD_NUMBER: builtins.int
    @property
    def reconnect_ins(self) -> global___ServerMessage.ReconnectIns: ...
    @property
    def get_properties_ins(self) -> global___ServerMessage.GetPropertiesIns: ...
    @property
    def get_parameters_ins(self) -> global___ServerMessage.GetParametersIns: ...
    @property
    def fit_ins(self) -> global___ServerMessage.FitIns: ...
    @property
    def evaluate_ins(self) -> global___ServerMessage.EvaluateIns: ...
    @property
    def send_sum_ins(self) -> global___ServerMessage.SendSumIns: ...
    @property
    def get_pk_ins(self) -> global___ServerMessage.GetPKIns: ...
    @property
    def send_pk_ins(self) -> global___ServerMessage.SendPKIns: ...
    @property
    def get_parms_ins(self) -> global___ServerMessage.GetParmsIns: ...
    @property
    def send_enc_ins(self) -> global___ServerMessage.SendEncIns: ...
    @property
    def send_ds_ins(self) -> global___ServerMessage.SendDSIns: ...
    @property
    def send_eval_ins(self) -> global___ServerMessage.SendEvalIns: ...
    @property
    def get_gradients_ins(self) -> global___ServerMessage.GetGradientsIns: ...
    @property
    def identify_ins(self) -> global___ServerMessage.IdentifyIns: ...
    @property
    def get_contributions_ins(self) -> global___ServerMessage.GetContributionsIns: ...
    @property
    def send_public_key_ins(self) -> global___ServerMessage.SendPublicKeyIns: ...
    def __init__(
        self,
        *,
        reconnect_ins: global___ServerMessage.ReconnectIns | None = ...,
        get_properties_ins: global___ServerMessage.GetPropertiesIns | None = ...,
        get_parameters_ins: global___ServerMessage.GetParametersIns | None = ...,
        fit_ins: global___ServerMessage.FitIns | None = ...,
        evaluate_ins: global___ServerMessage.EvaluateIns | None = ...,
        send_sum_ins: global___ServerMessage.SendSumIns | None = ...,
        get_pk_ins: global___ServerMessage.GetPKIns | None = ...,
        send_pk_ins: global___ServerMessage.SendPKIns | None = ...,
        get_parms_ins: global___ServerMessage.GetParmsIns | None = ...,
        send_enc_ins: global___ServerMessage.SendEncIns | None = ...,
        send_ds_ins: global___ServerMessage.SendDSIns | None = ...,
        send_eval_ins: global___ServerMessage.SendEvalIns | None = ...,
        get_gradients_ins: global___ServerMessage.GetGradientsIns | None = ...,
        identify_ins: global___ServerMessage.IdentifyIns | None = ...,
        get_contributions_ins: global___ServerMessage.GetContributionsIns | None = ...,
        send_public_key_ins: global___ServerMessage.SendPublicKeyIns | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["evaluate_ins", b"evaluate_ins", "fit_ins", b"fit_ins", "get_contributions_ins", b"get_contributions_ins", "get_gradients_ins", b"get_gradients_ins", "get_parameters_ins", b"get_parameters_ins", "get_parms_ins", b"get_parms_ins", "get_pk_ins", b"get_pk_ins", "get_properties_ins", b"get_properties_ins", "identify_ins", b"identify_ins", "msg", b"msg", "reconnect_ins", b"reconnect_ins", "send_ds_ins", b"send_ds_ins", "send_enc_ins", b"send_enc_ins", "send_eval_ins", b"send_eval_ins", "send_pk_ins", b"send_pk_ins", "send_public_key_ins", b"send_public_key_ins", "send_sum_ins", b"send_sum_ins"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["evaluate_ins", b"evaluate_ins", "fit_ins", b"fit_ins", "get_contributions_ins", b"get_contributions_ins", "get_gradients_ins", b"get_gradients_ins", "get_parameters_ins", b"get_parameters_ins", "get_parms_ins", b"get_parms_ins", "get_pk_ins", b"get_pk_ins", "get_properties_ins", b"get_properties_ins", "identify_ins", b"identify_ins", "msg", b"msg", "reconnect_ins", b"reconnect_ins", "send_ds_ins", b"send_ds_ins", "send_enc_ins", b"send_enc_ins", "send_eval_ins", b"send_eval_ins", "send_pk_ins", b"send_pk_ins", "send_public_key_ins", b"send_public_key_ins", "send_sum_ins", b"send_sum_ins"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["msg", b"msg"]) -> typing_extensions.Literal["reconnect_ins", "get_properties_ins", "get_parameters_ins", "fit_ins", "evaluate_ins", "send_sum_ins", "get_pk_ins", "send_pk_ins", "get_parms_ins", "send_enc_ins", "send_ds_ins", "send_eval_ins", "get_gradients_ins", "identify_ins", "get_contributions_ins", "send_public_key_ins"] | None: ...

global___ServerMessage = ServerMessage

@typing_extensions.final
class ClientMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class DisconnectRes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        REASON_FIELD_NUMBER: builtins.int
        reason: global___Reason.ValueType
        def __init__(
            self,
            *,
            reason: global___Reason.ValueType = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["reason", b"reason"]) -> None: ...

    @typing_extensions.final
    class GetPropertiesRes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class PropertiesEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            @property
            def value(self) -> global___Scalar: ...
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: global___Scalar | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

        STATUS_FIELD_NUMBER: builtins.int
        PROPERTIES_FIELD_NUMBER: builtins.int
        @property
        def status(self) -> global___Status: ...
        @property
        def properties(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Scalar]: ...
        def __init__(
            self,
            *,
            status: global___Status | None = ...,
            properties: collections.abc.Mapping[builtins.str, global___Scalar] | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["status", b"status"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["properties", b"properties", "status", b"status"]) -> None: ...

    @typing_extensions.final
    class GetParametersRes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        STATUS_FIELD_NUMBER: builtins.int
        PARAMETERS_FIELD_NUMBER: builtins.int
        @property
        def status(self) -> global___Status: ...
        @property
        def parameters(self) -> global___Parameters: ...
        def __init__(
            self,
            *,
            status: global___Status | None = ...,
            parameters: global___Parameters | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["parameters", b"parameters", "status", b"status"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["parameters", b"parameters", "status", b"status"]) -> None: ...

    @typing_extensions.final
    class FitRes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class MetricsEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            @property
            def value(self) -> global___Scalar: ...
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: global___Scalar | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

        STATUS_FIELD_NUMBER: builtins.int
        PARAMETERS_FIELD_NUMBER: builtins.int
        NUM_EXAMPLES_FIELD_NUMBER: builtins.int
        METRICS_FIELD_NUMBER: builtins.int
        @property
        def status(self) -> global___Status: ...
        @property
        def parameters(self) -> global___Parameters: ...
        num_examples: builtins.int
        @property
        def metrics(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Scalar]: ...
        def __init__(
            self,
            *,
            status: global___Status | None = ...,
            parameters: global___Parameters | None = ...,
            num_examples: builtins.int = ...,
            metrics: collections.abc.Mapping[builtins.str, global___Scalar] | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["parameters", b"parameters", "status", b"status"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["metrics", b"metrics", "num_examples", b"num_examples", "parameters", b"parameters", "status", b"status"]) -> None: ...

    @typing_extensions.final
    class EvaluateRes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class MetricsEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            @property
            def value(self) -> global___Scalar: ...
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: global___Scalar | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

        STATUS_FIELD_NUMBER: builtins.int
        LOSS_FIELD_NUMBER: builtins.int
        NUM_EXAMPLES_FIELD_NUMBER: builtins.int
        METRICS_FIELD_NUMBER: builtins.int
        @property
        def status(self) -> global___Status: ...
        loss: builtins.float
        num_examples: builtins.int
        @property
        def metrics(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Scalar]: ...
        def __init__(
            self,
            *,
            status: global___Status | None = ...,
            loss: builtins.float = ...,
            num_examples: builtins.int = ...,
            metrics: collections.abc.Mapping[builtins.str, global___Scalar] | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["status", b"status"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["loss", b"loss", "metrics", b"metrics", "num_examples", b"num_examples", "status", b"status"]) -> None: ...

    @typing_extensions.final
    class SendValRes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        STATUS_FIELD_NUMBER: builtins.int
        VAL_FIELD_NUMBER: builtins.int
        status: builtins.str
        val: builtins.int
        def __init__(
            self,
            *,
            status: builtins.str | None = ...,
            val: builtins.int = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["_status", b"_status", "status", b"status"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["_status", b"_status", "status", b"status", "val", b"val"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions.Literal["_status", b"_status"]) -> typing_extensions.Literal["status"] | None: ...

    @typing_extensions.final
    class GetShareRes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SHARE_FIELD_NUMBER: builtins.int
        @property
        def share(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        def __init__(
            self,
            *,
            share: collections.abc.Iterable[builtins.int] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["share", b"share"]) -> None: ...

    @typing_extensions.final
    class GetPKRes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CTX_FIELD_NUMBER: builtins.int
        ctx: builtins.bytes
        def __init__(
            self,
            *,
            ctx: builtins.bytes = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["ctx", b"ctx"]) -> None: ...

    @typing_extensions.final
    class SendPKRes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        STATUS_FIELD_NUMBER: builtins.int
        status: builtins.str
        def __init__(
            self,
            *,
            status: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["status", b"status"]) -> None: ...

    @typing_extensions.final
    class GetParmsRes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CTX_FIELD_NUMBER: builtins.int
        PARMS_FIELD_NUMBER: builtins.int
        ctx: builtins.bytes
        parms: builtins.bytes
        def __init__(
            self,
            *,
            ctx: builtins.bytes = ...,
            parms: builtins.bytes = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["ctx", b"ctx", "parms", b"parms"]) -> None: ...

    @typing_extensions.final
    class SendEncRes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CTX_FIELD_NUMBER: builtins.int
        DS_FIELD_NUMBER: builtins.int
        ctx: builtins.bytes
        ds: builtins.bytes
        def __init__(
            self,
            *,
            ctx: builtins.bytes = ...,
            ds: builtins.bytes = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["ctx", b"ctx", "ds", b"ds"]) -> None: ...

    @typing_extensions.final
    class SendDSRes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class MetricsEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            @property
            def value(self) -> global___Scalar: ...
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: global___Scalar | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

        CTX_FIELD_NUMBER: builtins.int
        ENC_FIELD_NUMBER: builtins.int
        LOSS_FIELD_NUMBER: builtins.int
        NUM_EXAMPLES_FIELD_NUMBER: builtins.int
        METRICS_FIELD_NUMBER: builtins.int
        ctx: builtins.bytes
        enc: builtins.bytes
        loss: builtins.float
        num_examples: builtins.int
        @property
        def metrics(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Scalar]: ...
        def __init__(
            self,
            *,
            ctx: builtins.bytes = ...,
            enc: builtins.bytes = ...,
            loss: builtins.float = ...,
            num_examples: builtins.int = ...,
            metrics: collections.abc.Mapping[builtins.str, global___Scalar] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["ctx", b"ctx", "enc", b"enc", "loss", b"loss", "metrics", b"metrics", "num_examples", b"num_examples"]) -> None: ...

    @typing_extensions.final
    class SendEvalRes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class MetricsEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            @property
            def value(self) -> global___Scalar: ...
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: global___Scalar | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

        LOSS_FIELD_NUMBER: builtins.int
        NUM_EXAMPLES_FIELD_NUMBER: builtins.int
        METRICS_FIELD_NUMBER: builtins.int
        loss: builtins.float
        num_examples: builtins.int
        @property
        def metrics(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Scalar]: ...
        def __init__(
            self,
            *,
            loss: builtins.float = ...,
            num_examples: builtins.int = ...,
            metrics: collections.abc.Mapping[builtins.str, global___Scalar] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["loss", b"loss", "metrics", b"metrics", "num_examples", b"num_examples"]) -> None: ...

    @typing_extensions.final
    class SendEvalLastRes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class MetricsEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            @property
            def value(self) -> global___Scalar: ...
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: global___Scalar | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

        LOSS_FIELD_NUMBER: builtins.int
        NUM_EXAMPLES_FIELD_NUMBER: builtins.int
        METRICS_FIELD_NUMBER: builtins.int
        loss: builtins.float
        num_examples: builtins.int
        @property
        def metrics(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Scalar]: ...
        def __init__(
            self,
            *,
            loss: builtins.float = ...,
            num_examples: builtins.int = ...,
            metrics: collections.abc.Mapping[builtins.str, global___Scalar] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["loss", b"loss", "metrics", b"metrics", "num_examples", b"num_examples"]) -> None: ...

    @typing_extensions.final
    class GetGradientsRes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        GRADIENTS_FIELD_NUMBER: builtins.int
        gradients: builtins.bytes
        def __init__(
            self,
            *,
            gradients: builtins.bytes = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["gradients", b"gradients"]) -> None: ...

    @typing_extensions.final
    class IdentifyRes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        STATUS_FIELD_NUMBER: builtins.int
        @property
        def status(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
        def __init__(
            self,
            *,
            status: collections.abc.Iterable[builtins.str] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["status", b"status"]) -> None: ...

    @typing_extensions.final
    class GetContributionsRes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CONTRIBUTIONS_FIELD_NUMBER: builtins.int
        @property
        def contributions(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
        def __init__(
            self,
            *,
            contributions: collections.abc.Iterable[builtins.float] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["contributions", b"contributions"]) -> None: ...

    @typing_extensions.final
    class SendPublicKeyRes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    DISCONNECT_RES_FIELD_NUMBER: builtins.int
    GET_PROPERTIES_RES_FIELD_NUMBER: builtins.int
    GET_PARAMETERS_RES_FIELD_NUMBER: builtins.int
    FIT_RES_FIELD_NUMBER: builtins.int
    EVALUATE_RES_FIELD_NUMBER: builtins.int
    SEND_VAL_RES_FIELD_NUMBER: builtins.int
    GET_SHARE_RES_FIELD_NUMBER: builtins.int
    GET_PK_RES_FIELD_NUMBER: builtins.int
    SEND_PK_RES_FIELD_NUMBER: builtins.int
    GET_PARMS_RES_FIELD_NUMBER: builtins.int
    SEND_ENC_RES_FIELD_NUMBER: builtins.int
    SEND_DS_RES_FIELD_NUMBER: builtins.int
    SEND_EVAL_RES_FIELD_NUMBER: builtins.int
    GET_GRADIENTS_RES_FIELD_NUMBER: builtins.int
    IDENTIFY_RES_FIELD_NUMBER: builtins.int
    GET_CONTRIBUTIONS_RES_FIELD_NUMBER: builtins.int
    SEND_PUBLIC_KEY_RES_FIELD_NUMBER: builtins.int
    @property
    def disconnect_res(self) -> global___ClientMessage.DisconnectRes: ...
    @property
    def get_properties_res(self) -> global___ClientMessage.GetPropertiesRes: ...
    @property
    def get_parameters_res(self) -> global___ClientMessage.GetParametersRes: ...
    @property
    def fit_res(self) -> global___ClientMessage.FitRes: ...
    @property
    def evaluate_res(self) -> global___ClientMessage.EvaluateRes: ...
    @property
    def send_val_res(self) -> global___ClientMessage.SendValRes: ...
    @property
    def get_share_res(self) -> global___ClientMessage.GetShareRes: ...
    @property
    def get_pk_res(self) -> global___ClientMessage.GetPKRes: ...
    @property
    def send_pk_res(self) -> global___ClientMessage.SendPKRes: ...
    @property
    def get_parms_res(self) -> global___ClientMessage.GetParmsRes: ...
    @property
    def send_enc_res(self) -> global___ClientMessage.SendEncRes: ...
    @property
    def send_ds_res(self) -> global___ClientMessage.SendDSRes: ...
    @property
    def send_eval_res(self) -> global___ClientMessage.SendEvalRes: ...
    @property
    def get_gradients_res(self) -> global___ClientMessage.GetGradientsRes: ...
    @property
    def identify_res(self) -> global___ClientMessage.IdentifyRes: ...
    @property
    def get_contributions_res(self) -> global___ClientMessage.GetContributionsRes: ...
    @property
    def send_public_key_res(self) -> global___ClientMessage.SendPublicKeyRes: ...
    def __init__(
        self,
        *,
        disconnect_res: global___ClientMessage.DisconnectRes | None = ...,
        get_properties_res: global___ClientMessage.GetPropertiesRes | None = ...,
        get_parameters_res: global___ClientMessage.GetParametersRes | None = ...,
        fit_res: global___ClientMessage.FitRes | None = ...,
        evaluate_res: global___ClientMessage.EvaluateRes | None = ...,
        send_val_res: global___ClientMessage.SendValRes | None = ...,
        get_share_res: global___ClientMessage.GetShareRes | None = ...,
        get_pk_res: global___ClientMessage.GetPKRes | None = ...,
        send_pk_res: global___ClientMessage.SendPKRes | None = ...,
        get_parms_res: global___ClientMessage.GetParmsRes | None = ...,
        send_enc_res: global___ClientMessage.SendEncRes | None = ...,
        send_ds_res: global___ClientMessage.SendDSRes | None = ...,
        send_eval_res: global___ClientMessage.SendEvalRes | None = ...,
        get_gradients_res: global___ClientMessage.GetGradientsRes | None = ...,
        identify_res: global___ClientMessage.IdentifyRes | None = ...,
        get_contributions_res: global___ClientMessage.GetContributionsRes | None = ...,
        send_public_key_res: global___ClientMessage.SendPublicKeyRes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["disconnect_res", b"disconnect_res", "evaluate_res", b"evaluate_res", "fit_res", b"fit_res", "get_contributions_res", b"get_contributions_res", "get_gradients_res", b"get_gradients_res", "get_parameters_res", b"get_parameters_res", "get_parms_res", b"get_parms_res", "get_pk_res", b"get_pk_res", "get_properties_res", b"get_properties_res", "get_share_res", b"get_share_res", "identify_res", b"identify_res", "msg", b"msg", "send_ds_res", b"send_ds_res", "send_enc_res", b"send_enc_res", "send_eval_res", b"send_eval_res", "send_pk_res", b"send_pk_res", "send_public_key_res", b"send_public_key_res", "send_val_res", b"send_val_res"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["disconnect_res", b"disconnect_res", "evaluate_res", b"evaluate_res", "fit_res", b"fit_res", "get_contributions_res", b"get_contributions_res", "get_gradients_res", b"get_gradients_res", "get_parameters_res", b"get_parameters_res", "get_parms_res", b"get_parms_res", "get_pk_res", b"get_pk_res", "get_properties_res", b"get_properties_res", "get_share_res", b"get_share_res", "identify_res", b"identify_res", "msg", b"msg", "send_ds_res", b"send_ds_res", "send_enc_res", b"send_enc_res", "send_eval_res", b"send_eval_res", "send_pk_res", b"send_pk_res", "send_public_key_res", b"send_public_key_res", "send_val_res", b"send_val_res"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["msg", b"msg"]) -> typing_extensions.Literal["disconnect_res", "get_properties_res", "get_parameters_res", "fit_res", "evaluate_res", "send_val_res", "get_share_res", "get_pk_res", "send_pk_res", "get_parms_res", "send_enc_res", "send_ds_res", "send_eval_res", "get_gradients_res", "identify_res", "get_contributions_res", "send_public_key_res"] | None: ...

global___ClientMessage = ClientMessage

@typing_extensions.final
class Scalar(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DOUBLE_FIELD_NUMBER: builtins.int
    SINT64_FIELD_NUMBER: builtins.int
    BOOL_FIELD_NUMBER: builtins.int
    STRING_FIELD_NUMBER: builtins.int
    BYTES_FIELD_NUMBER: builtins.int
    double: builtins.float
    sint64: builtins.int
    """float float = 2;
    int32 int32 = 3;
    int64 int64 = 4;
    uint32 uint32 = 5;
    uint64 uint64 = 6;
    sint32 sint32 = 7;
    """
    bool: builtins.bool
    """fixed32 fixed32 = 9;
    fixed64 fixed64 = 10;
    sfixed32 sfixed32 = 11;
    sfixed64 sfixed64 = 12;
    """
    string: builtins.str
    bytes: builtins.bytes
    def __init__(
        self,
        *,
        double: builtins.float = ...,
        sint64: builtins.int = ...,
        bool: builtins.bool = ...,
        string: builtins.str = ...,
        bytes: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["bool", b"bool", "bytes", b"bytes", "double", b"double", "scalar", b"scalar", "sint64", b"sint64", "string", b"string"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bool", b"bool", "bytes", b"bytes", "double", b"double", "scalar", b"scalar", "sint64", b"sint64", "string", b"string"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["scalar", b"scalar"]) -> typing_extensions.Literal["double", "sint64", "bool", "string", "bytes"] | None: ...

global___Scalar = Scalar
